### ISSUE TITLE
Content (Page Title) is reflecting in footer

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Edric-Internal---Speed-Work-9th-May-#1]
The content is reflecting in footer.
https://wha79yyvr31pyxrw-10186948655.shopifypreview.com/

![image](https://user-images.githubusercontent.com/97726944/167767308-908dd0ce-5e17-44b6-b62e-18736d8deae1.png)

https://wha79yyvr31pyxrw-10186948655.shopifypreview.com/collections/face
![image](https://user-images.githubusercontent.com/97726944/167767537-e3ca1bf7-8c6a-4557-89d9-fe980fc4541c.png)

**Comment by Ataurrahman-khan** [comment]
Issues Resolved
